[package]
name = "minecraft-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
minecraft_query = "0.1.2"
tokio = "1.17.0"
rocket-include-static-resources = "0.10.1"
